### ISSUE TITLE
启动alispot.exe报错,报错信息如下...为啥会报错呀..

### ISSUE THREAD

**Issue by wyfxiaowangzi** [rockswang/alispot#12]
"err":{"message":"Cannot read property 'port' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'port' of undefined\n    at main (E:\\myssr\\index.js:276:26)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"msg":"Cannot read property 'port' of undefined","time":"2021-03-13T01:31:58.753Z","v":0}

**Comment by rockswang** [comment]
因为内容敏感，完整文档和代码在forward.js分支，请仔细阅读。
