### ISSUE TITLE
最近经常启动报错，似乎是专有网络问题

### ISSUE THREAD

**Issue by MgArcher** [rockswang/alispot#14]
日志如下：
{"name":"alispot","hostname":"DESKTOP-6J8LG75","pid":16380,"level":20,"result":{"RequestId":"66F2DC1B-29A7-55C7-AAC1-501E40015E40","Regions":{"Region":[{"RegionId":"cn-qingdao","RegionEndpoint":"ecs.cn-qingdao.aliyuncs.com","LocalName":"华北1（青岛）"},{"RegionId":"cn-beijing","RegionEndpoint":"ecs.cn-beijing.aliyuncs.com","LocalName":"华北2（北京）"},{"RegionId":"cn-zhangjiakou","RegionEndpoint":"ecs.cn-zhangjiakou.aliyuncs.com","LocalName":"华北3（张家口）"},{"RegionId":"cn-huhehaote","RegionEndpoint":"ecs.cn-huhehaote.aliyuncs.com","LocalName":"华北5（呼和浩特）"},{"RegionId":"cn-wulanchabu","RegionEndpoint":"ecs.cn-wulanchabu.aliyuncs.com","LocalName":"华北6（乌兰察布）"},{"RegionId":"cn-hangzhou","RegionEndpoint":"ecs.aliyuncs.com","LocalName":"华东1（杭州）"},{"RegionId":"cn-shanghai","RegionEndpoint":"ecs.cn-shanghai.aliyuncs.com","LocalName":"华东2（上海）"},{"RegionId":"cn-shenzhen","RegionEndpoint":"ecs.cn-shenzhen.aliyuncs.com","LocalName":"华南1（深圳）"},{"RegionId":"cn-heyuan","RegionEndpoint":"ecs.cn-heyuan.aliyuncs.com","LocalName":"华南2（河源）"},{"RegionId":"cn-guangzhou","RegionEndpoint":"ecs.cn-guangzhou.aliyuncs.com","LocalName":"华南3（广州）"},{"RegionId":"cn-chengdu","RegionEndpoint":"ecs.cn-chengdu.aliyuncs.com","LocalName":"西南1（成都）"},{"RegionId":"cn-hongkong","RegionEndpoint":"ecs.cn-hongkong.aliyuncs.com","LocalName":"中国（香港）"},{"RegionId":"ap-northeast-1","RegionEndpoint":"ecs.ap-northeast-1.aliyuncs.com","LocalName":"亚太东北 1 (东京)"},{"RegionId":"ap-southeast-1","RegionEndpoint":"ecs.ap-southeast-1.aliyuncs.com","LocalName":"亚太东南 1 (新加坡)"},{"RegionId":"ap-southeast-2","RegionEndpoint":"ecs.ap-southeast-2.aliyuncs.com","LocalName":"亚太东南 2 (悉尼)"},{"RegionId":"ap-southeast-3","RegionEndpoint":"ecs.ap-southeast-3.aliyuncs.com","LocalName":"亚太东南 3 (吉隆坡)"},{"RegionId":"ap-southeast-6","RegionEndpoint":"ecs.ap-southeast-6.aliyuncs.com","LocalName":"菲律宾（马尼拉）"},{"RegionId":"ap-southeast-5","RegionEndpoint":"ecs.ap-southeast-5.aliyuncs.com","LocalName":"亚太东南 5 (雅加达)"},{"RegionId":"ap-south-1","RegionEndpoint":"ecs.ap-south-1.aliyuncs.com","LocalName":"亚太南部 1 (孟买)"},{"RegionId":"us-east-1","RegionEndpoint":"ecs.aliyuncs.com","LocalName":"美国东部 1 (弗吉尼亚)"},{"RegionId":"us-west-1","RegionEndpoint":"ecs.aliyuncs.com","LocalName":"美国西部 1 (硅谷)"},{"RegionId":"eu-west-1","RegionEndpoint":"ecs.eu-west-1.aliyuncs.com","LocalName":"英国 (伦敦)"},{"RegionId":"me-east-1","RegionEndpoint":"ecs.me-east-1.aliyuncs.com","LocalName":"中东东部 1 (迪拜)"},{"RegionId":"eu-central-1","RegionEndpoint":"ecs.eu-central-1.aliyuncs.com","LocalName":"欧洲中部 1 (法兰克福)"},{"RegionId":"cn-nanjing","RegionEndpoint":"ecs.cn-nanjing.aliyuncs.com","LocalName":"华东5（南京-本地地域）"}]}},"msg":"DescribeRegions","time":"2021-12-16T06:54:31.514Z","v":0}
{"name":"alispot","hostname":"DESKTOP-6J8LG75","pid":16380,"level":30,"msg":"地域\"ap-southeast-1\"的API地址：\"https://ecs.ap-southeast-1.aliyuncs.com\"","time":"2021-12-16T06:54:31.514Z","v":0}
{"name":"alispot","hostname":"DESKTOP-6J8LG75","pid":16380,"level":20,"result":{"RequestId":"DA57E40D-B490-3E58-9236-8A265AB3FBFE","Currency":"CNY","SpotPrices":{"SpotPriceType":[{"SpotPrice":0.011,"OriginPrice":0.105,"IoOptimized":"optimized","ZoneId":"ap-southeast-1a","NetworkType":"vpc","InstanceType":"ecs.xn4.small","Timestamp":"2021-12-16T04:00:00Z"},{"SpotPrice":0.011,"OriginPrice":0.105,"IoOptimized":"optimized","ZoneId":"ap-southeast-1a","NetworkType":"vpc","InstanceType":"ecs.xn4.small","Timestamp":"2021-12-16T05:00:00Z"},{"SpotPrice":0.011,"OriginPrice":0.105,"IoOptimized":"optimized","ZoneId":"ap-southeast-1a","NetworkType":"vpc","InstanceType":"ecs.xn4.small","Timestamp":"2021-12-16T06:00:00Z"},{"SpotPrice":0.011,"OriginPrice":0.105,"IoOptimized":"optimized","ZoneId":"ap-southeast-1b","NetworkType":"vpc","InstanceType":"ecs.xn4.small","Timestamp":"2021-12-16T04:00:00Z"},{"SpotPrice":0.011,"OriginPrice":0.105,"IoOptimized":"optimized","ZoneId":"ap-southeast-1b","NetworkType":"vpc","InstanceType":"ecs.xn4.small","Timestamp":"2021-12-16T05:00:00Z"},{"SpotPrice":0.011,"OriginPrice":0.105,"IoOptimized":"optimized","ZoneId":"ap-southeast-1b","NetworkType":"vpc","InstanceType":"ecs.xn4.small","Timestamp":"2021-12-16T06:00:00Z"},{"SpotPrice":0.096,"OriginPrice":0.105,"IoOptimized":"optimized","ZoneId":"ap-southeast-1c","NetworkType":"vpc","InstanceType":"ecs.xn4.small","Timestamp":"2021-12-16T04:00:00Z"},{"SpotPrice":0.097,"OriginPrice":0.105,"IoOptimized":"optimized","ZoneId":"ap-southeast-1c","NetworkType":"vpc","InstanceType":"ecs.xn4.small","Timestamp":"2021-12-16T05:00:00Z"},{"SpotPrice":0.098,"OriginPrice":0.105,"IoOptimized":"optimized","ZoneId":"ap-southeast-1c","NetworkType":"vpc","InstanceType":"ecs.xn4.small","Timestamp":"2021-12-16T06:00:00Z"}]}},"msg":"DescribeSpotPriceHistory","time":"2021-12-16T06:54:31.961Z","v":0}
{"name":"alispot","hostname":"DESKTOP-6J8LG75","pid":16380,"level":30,"msg":"地域\"ap-southeast-1\"抢占式实例价格最低的可用区：\"ap-southeast-1a\"","time":"2021-12-16T06:54:31.961Z","v":0}
{"name":"alispot","hostname":"DESKTOP-6J8LG75","pid":16380,"level":20,"result":{"SecurityGroups":{"SecurityGroup":[{"Description":"","VpcId":"vpc-t4n23t7umnbgms8h0h644","ServiceManaged":false,"SecurityGroupName":"alispotCreatedSecurityGroup","ResourceGroupId":"","SecurityGroupId":"sg-t4n6fszc0i8lcfavhba3","CreationTime":"2021-12-15T01:32:49Z","SecurityGroupType":"normal","Tags":{"Tag":[]}}]},"TotalCount":1,"PageSize":10,"RequestId":"84B40434-AFA3-3A60-95AF-FA9957FBE181","PageNumber":1,"RegionId":"ap-southeast-1"},"msg":"DescribeSecurityGroups","time":"2021-12-16T06:54:32.054Z","v":0}
{"name":"alispot","hostname":"DESKTOP-6J8LG75","pid":16380,"level":30,"msg":"VpcId: vpc-t4n23t7umnbgms8h0h644, SecurityGroupId: sg-t4n6fszc0i8lcfavhba3","time":"2021-12-16T06:54:32.054Z","v":0}
{"name":"alispot","hostname":"DESKTOP-6J8LG75","pid":16380,"level":20,"result":[{"RequestId":"2DF6654E-75BE-368C-9003-A9C3D39B86B4"},{"RequestId":"4DF4C0AE-44C0-31E8-81E0-557D5970B0E7"},{"RequestId":"2BFA42DE-41D8-3895-A407-F2C69F9B4971"},{"RequestId":"48D5341E-2398-3396-9723-22B66E3FB696"},{"RequestId":"E74E8E42-7DA8-3CEB-8DC6-D6A782B30148"}],"msg":"AuthorizeSecurityGroup","time":"2021-12-16T06:54:32.452Z","v":0}
{"name":"alispot","hostname":"DESKTOP-6J8LG75","pid":16380,"level":30,"msg":"为安全组sg-t4n6fszc0i8lcfavhba3开启端口","time":"2021-12-16T06:54:32.452Z","v":0}
{"name":"alispot","hostname":"DESKTOP-6J8LG75","pid":16380,"level":20,"result":{"TotalCount":0,"PageSize":10,"RequestId":"C10B8D14-FE93-52B0-8166-0959244AD2CB","PageNumber":1,"VSwitches":{"VSwitch":[]}},"msg":"DescribeVSwitches","time":"2021-12-16T06:54:32.634Z","v":0}
{"name":"alispot","hostname":"DESKTOP-6J8LG75","pid":16380,"level":30,"msg":"创建VSwitch ap-southeast-1","time":"2021-12-16T06:54:32.634Z","v":0}
{"name":"alispot","hostname":"DESKTOP-6J8LG75","pid":16380,"level":60,"err":{"message":"Specified CIDR block overlapped with other subnets., URL: https://ecs.ap-southeast-1.aliyuncs.com/","name":"InvalidCidrBlock.OverlappedError","stack":"InvalidCidrBlock.OverlappedError: Specified CIDR block overlapped with other subnets., URL: https://ecs.ap-southeast-1.aliyuncs.com/\n    at httpx.request.then.then (C:\\ShadowsocksR-4.7.0-win\\node_modules\\@alicloud\\pop-core\\lib\\rpc.js:205:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","code":"InvalidCidrBlock.Overlapped"},"msg":"Specified CIDR block overlapped with other subnets., URL: https://ecs.ap-southeast-1.aliyuncs.com/","time":"2021-12-16T06:54:32.891Z","v":0}

**Comment by rockswang** [comment]
>重复调用CreateVpc了，你可以登上去把脚本创建的VPC和安全组都删掉，再试试
见 #10
